Transform: AWS::Serverless-2016-10-31
Parameters:
  CurrentAPIEnv:
    Description: CurrentsAPI Parameter (To be stored in Lambda Environment Variables)
    Type: String
    Default: 0
Resources:
  crosslinkTypeScript:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: crosslinkTypeScript
      Environment:
        Variables:
          API_KEY: { "Ref" : "CurrentAPIEnv" }
      InlineCode: |
        exports.handler = async (event) => {
          /* This is handle automatically by the API Gateway defined routes */
          /*
           Header and Required Information Checking
          */
          /* API Key Check */
          const apiKey = process.env.API_KEY;
          if (!apiKey) {
            return {
              statusCode: 500,
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ error: 'API Key Missing. Ask service administrator for help!' })
            };
          }
          /* Page Size */
          let pageSizeHeader = event.headers["pageSize"] || event.headers["pagesize"];
          let pageSize = parseInt(pageSizeHeader, 10);
          if (pageSizeHeader && isNaN(pageSize)) {
            return {
              statusCode: 400,
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ error: 'Error pageSize is not a number! Correct Fields and try again' })
            }
          } else if (pageSize > 50 || pageSize < 0) {
            return {
              statusCode: 400,
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ error: 'Error! pageSize improper value. Please set pageSize to 0 < x < 50' })
            }
          }
          /* Page Number */
          const pageNumberHeader = event.headers["page"] || event.headers["Page"];
          let pageNumber = parseInt(pageNumberHeader, 10);
          if (pageNumberHeader && isNaN(pageNumber)) {
            return {
              statusCode: 400,
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ error: 'Error page is not a number! Correct Fields and try again' })
            }
          } else if(pageNumber > 180 || pageNumber < 0) {
            return {
              statusCode: 400,
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ error: 'Error! page improper value. Please set page to 0 < x < 180' })
            }
          }
          if(pageSize && pageNumber && (((pageNumber - 1) * pageSize) > 5000)) {
            return {
              statusCode: 400,
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ error: 'Error! page * pageSize value too large. Max value total value is 5000 (CurrentsAPI Hard Limit)' })
          }
        }
        /* Keywords validation */
          const keywords = event.headers["keywords"] || event.headers["Keywords"];
          if(keywords && keywords.length > 100) {
            return {
              statusCode: 400,
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ error: 'Error keywords exceed 100 character limit' })
            }
          }
          try {
            /*Dynamically Create the API Request link based on potentially added headers. Omit if not there */
            let apiRequestLink = ("https://api.currentsapi.services/v1/" + (keywords ? "search" : "latest-news") + "?language=en" + (keywords ? ("&keywords="+keywords) : "") + (pageSize ? ("&page_size=" + pageSize) : "&page_size=5") + (pageNumber ? ("&page_number=" + pageNumber) : "&page_number=1"));
            const response = await fetch(apiRequestLink, {
              headers: {
                'Authorization': apiKey
              }
            });
            if (!response.ok) { /*Terminate if a valid response wasn't returned*/
              return {
                statusCode: response.status,
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ error: `Error! reqLink: ${apiRequestLink} headers: pageSize: ${pageSize} page: ${pageNumber} status: ${response.status}` })
              };
            }
            const data = await response.json();
            return {
              statusCode: 200,
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify(data)
            };
          } catch (error) {
            return {
              statusCode: 500,
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ error: error.message })
            };
          }
        };

      Handler: index.handler
      Runtime: nodejs22.x
      MemorySize: 3008
      Timeout: 30
      Role: !GetAtt SharedLambdaExecutionRole.Arn
      Tracing: Active
      Events:
        crossLinkAPIGETts:
          Type: Api
          Properties:
            Path: /ts
            Method: GET
            RestApiId: !Ref crossLinkAPI
            Auth:
              Authorizer: CognitoAuth
            RequestParameters:
              - method.request.header.pageSize:
                  Required: false
                  Caching: false
              - method.request.header.page:
                  Required: false
                  Caching: false
  crosslinkTypeScriptLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${crosslinkTypeScript}
  crossLinkAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: crossLinkAPI
      StageName: Prod
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      Cors:
        MaxAge: 5
      Auth:
        Authorizers:
          CognitoAuth:
            UserPoolArn: !GetAtt CrosslinkUserPool.Arn
            Identity:
              Header: Authorization
  CrosslinkUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AliasAttributes:
        - email
      UserPoolName: !Sub ${AWS::StackName}-CrosslinkUserPool
  crosslinkPython:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: crosslinkPython
      InlineCode: |
        import requests
        headers = {
          'Authorization': process.env.API_KEY
        }
        response = requests.get(
          'https://api.currentsapi.services/v1/latest-news',
          headers=headers
        )
        data = response.json()
        return data
      Handler: index.handler
      Runtime: python3.13
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Role: !GetAtt SharedLambdaExecutionRole.Arn
      Events:
        crossLinkAPIGETpy:
          Type: Api
          Properties:
            Path: /py
            Method: GET
            RestApiId: !Ref crossLinkAPI
            Auth:
              Authorizer: CognitoAuth
  crosslinkPythonLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${crosslinkPython}

  SharedLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      # Here is where you attach that exact policy you saw in the console
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole